version: '3'
services:
   app:
      image: remialban/suivicovid
      restart: always
      ports:
         - "8000:80"
      links:
         - typesense:typesense
   typesense:
      image: typesense/typesense:0.20.0
      restart: always
      environment:
         TYPESENSE_API_KEY: Hu52dwsas2AdxdE
         TYPESENSE_DATA_DIR: /data
      volumes:
         - /tmp/data:/data
